[package]
name = "dopamine"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[lints]
workspace = true

[dependencies]
windows.workspace = true
serde.workspace = true
strum.workspace = true
log.workspace = true

dopamine-sdk.path = "../dopamine-sdk"

imgui.path = "../imgui"
imgui-dx9-renderer.path = "../imgui-dx9-renderer"
imgui-win32-support.path = "../imgui-win32-support"

educe = { version = "0.6.0", features = ["Default"] }
enum-map = { version = "2.7.3", features = ["serde"] }
fastrand = "2.1.0"
serde_yaml_ng = "0.10.0"
chrono = "0.4.38"
