[package]
name = "dopamine"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
dopamine-macros = { path = "../dopamine-macros" }

enum-map = { version = "2.7.3", features = ["serde"] }
num-traits = "0.2.19"
derive_builder = "0.20.0"
regex = "1.10.4"
fastrand = "2.1.0"
serde = { version = "1.0.200", features = ["derive"] }
toml = "0.8.12"
windows = { version = "0.56.0", features = [
    "Win32_System_Memory",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemServices",
    "Win32_System_ProcessStatus",
    "Win32_Graphics_Direct3D9",
    "Win32_Graphics_Gdi",
] }
