[package]
name = "dopamine-sdk"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
windows.workspace = true
strum.workspace = true
log.workspace = true
serde.workspace = true
derive_builder.workspace = true
bumpalo.workspace = true

dopamine-macros.path = "../dopamine-macros"

num-traits = "0.2"
minhook = "0.9"
open-enum = { version = "0.5", features = ["std"] }
